title: Miralda Sanchez # your name (or website title) here
logo: "/images/MiraldaXein6.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Digital CreativePreneur 
  <br><br>
  Musician 
  <br><br>
  <a href="https://www.linkedin.com/in/miraldasanchez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-145790415-1 # your Google Analytics tracking ID here
